import { test, expect } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

// Ensure screenshots directory exists
const screenshotsDir = path.join(__dirname, "../playwright-screenshots");
if (!fs.existsSync(screenshotsDir)) {
  fs.mkdirSync(screenshotsDir, { recursive: true });
}

test.describe.configure({ mode: "serial" });

test.describe("IT Ticket Dashboard E2E Tests", () => {
  test("1. Initial Load & Summary Cards Verification", async ({ page }) => {
    await page.goto("/");

    // Verify title/header
    await expect(page.locator("h1")).toHaveText("Ticket Dashboard");
    await expect(page.getByText("Internal IT Support")).toBeVisible();

    // Verify summary cards
    const totalCard = page.locator("article", { hasText: "Total Tickets" });
    const openCard = page.locator("article", { hasText: "Open Tickets" });
    const inProgressCard = page.locator("article", { hasText: "In Progress Tickets" });
    const highPriorityCard = page.locator("article", { hasText: "High Priority Tickets" });

    await expect(totalCard.locator("p").nth(1)).toHaveText("10");
    await expect(openCard.locator("p").nth(1)).toHaveText("3");
    await expect(inProgressCard.locator("p").nth(1)).toHaveText("3");
    await expect(highPriorityCard.locator("p").nth(1)).toHaveText("4");

    // Verify initial ticket list size
    const rows = page.locator("table tbody tr");
    await expect(rows).toHaveCount(10);

    // Take screenshot
    await page.screenshot({ path: path.join(screenshotsDir, "dashboard-initial.png") });
  });

  test("2. Add new ticket (Create)", async ({ page }) => {
    await page.goto("/");

    // Click Add Ticket button
    await page.click('a:has-text("Add Ticket")');
    await expect(page).toHaveURL(/\/tickets\/new/);
    await expect(page.locator("h1")).toHaveText("Add Ticket");

    // Fill form
    await page.fill('input[name="title"]', "E2E Test Playwright Ticket");
    await page.selectOption('select[name="category"]', "Network");
    await page.selectOption('select[name="priority"]', "Critical");
    await page.selectOption('select[name="status"]', "Open");
    await page.fill('input[name="assignedPerson"]', "Adit E2E");
    await page.fill('textarea[name="notes"]', "This is a test notes generated by Playwright.");

    // Take screenshot of filled form
    await page.screenshot({ path: path.join(screenshotsDir, "ticket-new-form.png") });

    // Submit
    await page.click('button[type="submit"]:has-text("Create Ticket")');

    // Should redirect to dashboard
    await expect(page).toHaveURL("/");

    // Verify dashboard cards increment
    const totalCard = page.locator("article", { hasText: "Total Tickets" });
    const openCard = page.locator("article", { hasText: "Open Tickets" });
    const highPriorityCard = page.locator("article", { hasText: "High Priority Tickets" });

    await expect(totalCard.locator("p").nth(1)).toHaveText("11");
    await expect(openCard.locator("p").nth(1)).toHaveText("4");
    // Critical is counted as high priority
    await expect(highPriorityCard.locator("p").nth(1)).toHaveText("5");

    // Verify new ticket appears in list (newest first by default)
    const firstRow = page.locator("table tbody tr").first();
    await expect(firstRow.locator("td").nth(0).locator("p").first()).toHaveText("E2E Test Playwright Ticket");
    await expect(firstRow.locator("td").nth(4)).toHaveText("Adit E2E");

    // Take screenshot of dashboard after create
    await page.screenshot({ path: path.join(screenshotsDir, "dashboard-after-create.png") });
  });

  test("3. Search and filter tickets", async ({ page }) => {
    await page.goto("/");

    // Fill search input
    await page.fill('input[name="search"]', "E2E Test Playwright");
    await page.click('button[type="submit"]:has-text("Apply")');

    // Verify count in list shows 1 of 11
    await expect(page.getByText("Showing 1 of 11 tickets")).toBeVisible();
    await expect(page.locator("table tbody tr")).toHaveCount(1);

    // Reset search
    await page.click('a:has-text("Reset")');
    await expect(page.getByText("Showing 11 of 11 tickets")).toBeVisible();

    // Filter by category: Network
    await page.selectOption('select[name="category"]', "Network");
    await page.click('button[type="submit"]:has-text("Apply")');

    // Verify Network count (originally 3 Network tickets: WiFi, VPN, Shared drive + 1 new Network ticket = 4)
    await expect(page.getByText("Showing 4 of 11 tickets")).toBeVisible();
    
    // Take screenshot of filtered results
    await page.screenshot({ path: path.join(screenshotsDir, "dashboard-filtered.png") });

    // Reset again
    await page.click('a:has-text("Reset")');
  });

  test("4. Edit ticket status (Update)", async ({ page }) => {
    await page.goto("/");

    // We want to edit the first ticket (our created one: "E2E Test Playwright Ticket")
    const firstRow = page.locator("table tbody tr").first();
    await expect(firstRow.locator("td").nth(0).locator("p").first()).toHaveText("E2E Test Playwright Ticket");
    
    // Click Edit link in first row
    await firstRow.locator('a:has-text("Edit")').click();
    await expect(page.locator("h1")).toHaveText("Edit Ticket");

    // Change status to Closed (Open -> Closed) and priority to Low (Critical -> Low)
    await page.selectOption('select[name="status"]', "Closed");
    await page.selectOption('select[name="priority"]', "Low");

    // Save changes
    await page.click('button[type="submit"]:has-text("Save Changes")');

    // Redirect to dashboard
    await expect(page).toHaveURL("/");

    // Verify dashboard cards recalculate:
    // Total should still be 11
    // Open should decrease by 1 (4 -> 3)
    // High priority should decrease by 1 (5 -> 4, since E2E ticket went Critical -> Low)
    const totalCard = page.locator("article", { hasText: "Total Tickets" });
    const openCard = page.locator("article", { hasText: "Open Tickets" });
    const highPriorityCard = page.locator("article", { hasText: "High Priority Tickets" });

    await expect(totalCard.locator("p").nth(1)).toHaveText("11");
    await expect(openCard.locator("p").nth(1)).toHaveText("3");
    await expect(highPriorityCard.locator("p").nth(1)).toHaveText("4");

    // Take screenshot
    await page.screenshot({ path: path.join(screenshotsDir, "dashboard-after-edit.png") });
  });

  test("5. Delete ticket (Delete)", async ({ page }) => {
    await page.goto("/");

    // We want to delete the first ticket ("E2E Test Playwright Ticket")
    const firstRow = page.locator("table tbody tr").first();
    await expect(firstRow.locator("td").nth(0).locator("p").first()).toHaveText("E2E Test Playwright Ticket");

    // Open the custom confirmation modal and confirm deletion.
    await firstRow.locator('button:has-text("Delete")').click();
    await expect(page.getByRole("dialog", { name: "Delete ticket?" })).toBeVisible();
    await expect(page.getByRole("dialog")).toContainText("E2E Test Playwright Ticket");
    await page.getByRole("button", { name: "Delete Ticket" }).click();

    // Verify ticket is removed (table count back to 10)
    await expect(page.locator("table tbody tr")).toHaveCount(10);
    
    // Verify stats update: Total 11 -> 10
    const totalCard = page.locator("article", { hasText: "Total Tickets" });
    await expect(totalCard.locator("p").nth(1)).toHaveText("10");

    // Take screenshot
    await page.screenshot({ path: path.join(screenshotsDir, "dashboard-after-delete.png") });
  });
});
